name: Release
run-name: Create Release
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update -q && sudo apt-get install gettext
      - run: bash scripts/build.sh
      - uses: svenstaro/upload-release-action@2.5.0
        with:
          file: tiling-assistant@leleat-on-github.shell-extension.zip
          overwrite: true
          release_name: Tiling Assistant ${{ github.ref_name }}
          body: 'Read about all the changes [here](https://github.com/Leleat/Tiling-Assistant/blob/main/CHANGELOG.md#${{ github.ref_name }}).'
